#ifndef RECEIVE_KEY_LAYER_H
#define RECEIVE_KEY_LAYER_H

// Received variables
#define WEATHER_KEY_TEMPERATURE 0
#define WEATHER_KEY_ICON 1
#define WEATHER_KEY_TODAY_MIN 2
#define WEATHER_KEY_TODAY_MAX 3
#define WEATHER_KEY_SUNRISE 4
#define WEATHER_KEY_SUNSET 5
#define WEATHER_KEY_TODAY_ICON 6
#define WEATHER_KEY_TOM_MIN 7 //tomorrow
#define WEATHER_KEY_TOM_MAX 8
#define WEATHER_KEY_TOM_ICON 9

#define NUM_TERMS 11
#define TERM_LEN 5

#endif
