#ifndef RECEIVE_KEY_LAYER_H
#define RECEIVE_KEY_LAYER_H

// Received variables
#define WEATHER_KEY_TEMPERATURE 1
#define WEATHER_KEY_ICON 2
#define WEATHER_KEY_TODAY_MIN 3
#define WEATHER_KEY_TODAY_MAX 4
#define WEATHER_KEY_SUNRISE 5
#define WEATHER_KEY_SUNSET 6
#define WEATHER_KEY_TODAY_ICON 7
#define WEATHER_KEY_TOM_MIN 8 //tomorrow
#define WEATHER_KEY_TOM_MAX 9
#define WEATHER_KEY_TOM_ICON 10

#define NUM_TERMS 10
#define TERM_LEN 5

#endif
